Create translation.json
Synthetixio/synthetix-translations pull request #1
Opened 2019-10-29 19:48 UTC by mmax2001

Spanish translate

2019-10-29 19:50 UTC, mmax2001 commented
Add Spanish translation for mintr

2019-10-29 23:47 UTC, clementbalestrat commented
@mmax2001 thanks! Can you please rename the `sp` folder to `es` to follow the ISO 639-1 standards?

Then we'll review the translation and merge it if everything is ok.

2019-10-29 23:55 UTC, mmax2001 commented
Yes of course!

El 29 oct. 2019, a la(s) 20:47, Clément BALESTRAT <notifications@github.com> escribió:

> @mmax2001 thanks! Can you please rename the sp folder to es to follow the ISO 639-1 standards?
> 
> Then we'll review the translation and merge it if everything is ok.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-10-30 00:15 UTC, 0xclem requested changes

2019-10-30 00:15 UTC, 0xclem commented on synthetix-mintr/sp/translation.json
> +{
You can now delete this file. Git still thinks there's a `sp/translation.json`

2019-10-30 00:42 UTC, clementbalestrat commented
@mmax2001 Sorry I should have mentioned how to do it. 

Can you please remove the changes in the `gitignore` as we don't want to edit this file.

If you have git installed in command line you can try something like `git rm sp/translation.json` instead. If still no luck don't worry I'll take care of that.

2019-10-30 00:58 UTC, mmax2001 commented
Ok, no problem!


El 29 oct. 2019, a la(s) 21:42, Clément BALESTRAT <notifications@github.com> escribió:

> @mmax2001 Sorry I should have mentioned how to do it.
> 
> Can you please remove the changes in the gitignore as we don't want to edit this file.
> 
> If you have git installed in command line you can try something like git rm sp/translation.json instead. If still no luck don't worry I'll take care of that.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-01 04:50 UTC, clementbalestrat commented
Hey @mmax2001 , thanks for your PR. Because of the next release we had to make some minor changes to the initial EN json file. Would you mind fixing your PR so it can use the latest updates?

Easiest way would be to start again from the new en/translation.json file as its structure changed a bit. Sorry again for the inconvenience.

FYI, here are the changes: https://github.com/Synthetixio/synthetix-translations/pull/3/files#diff-6000b66f2ed7c8f8c4e193a38d780897

2019-11-02 03:04 UTC, mmax2001 commented
> Hey @mmax2001 , thanks for your PR. Because of the next release we had to make some minor changes to the initial EN json file. Would you mind fixing your PR so it can use the latest updates?
> 
> Easiest way would be to start again from the new en/translation.json file as its structure changed a bit. Sorry again for the inconvenience.
> 
> FYI, here are the changes: https://github.com/Synthetixio/synthetix-translations/pull/3/files#diff-6000b66f2ed7c8f8c4e193a38d780897

New translatation is uploaded

2019-11-02 22:53 UTC, 0xclem requested changes
@mmax2001 Keep `node_modules`. `.gitignore` shouldn't be changed at all in the PR.

2019-11-03 03:43 UTC, mmax2001 commented
> shouldn't be changed at all in the PR.

how to keep these files in my fork?

2019-11-03 23:20 UTC, clementbalestrat commented
Thanks @mmax2001. Unfortunately there is now 7 files committed in the PR instead of 1, so I'll just close it and do a release with your translation file. Will keep you updated!

2019-11-04 03:14 UTC, mmax2001 commented
Oh I’m sorry! 
Thanks in advance!


El 3 nov. 2019, a la(s) 20:24, Clément BALESTRAT <notifications@github.com> escribió:

> Closed #1.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-08 15:36 UTC, mmax2001 commented
Hi Clément! I found a minor few issues in the translate, so I have fixed it .


El 3 nov. 2019, a la(s) 20:24, Clément BALESTRAT <notifications@github.com> escribió:

> Closed #1.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-09 00:14 UTC, clementbalestrat commented
Hi @mmax2001, thanks! Can you please create a new Pull request with your change? Make sure you only commit one file :)

2019-11-09 00:14 UTC, closed without merging